spring.application.name=demo

# Initialize schema.sql & data.sql
spring.sql.init.mode=always

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=12345
spring.sql.init.encoding=UTF-8

# Show H2 web console
spring.h2.console.enabled=true

# prevent Hibernate from altering schema
spring.jpa.hibernate.ddl-auto=none