server:
  servlet:
    context-path: /demo
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/mydb
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update