INSERT INTO EMPLOYEE (ID, DEPARTMENT_ID, NAME, AGE) VALUES (1, 1, 'John', 22);
INSERT INTO EMPLOYEE (ID, DEPARTMENT_ID, NAME, AGE) VALUES (2, 1, 'Mary', 25);
INSERT INTO EMPLOYEE (ID, DEPARTMENT_ID, NAME, AGE) VALUES (3, 2, 'Andy', 33);